# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-09 19:34
from __future__ import unicode_literals
import sys

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


if 'django_nose' in settings.INSTALLED_APPS or 'test' in sys.argv:

    class Migration(migrations.Migration):

        dependencies = [
            ('eav', '0001_initial'),
        ]

        operations = [
            migrations.CreateModel(
                name='Encounter',
                fields=[
                    ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                    ('num', models.PositiveSmallIntegerField()),
                ],
            ),
            migrations.CreateModel(
                name='Patient',
                fields=[
                    ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                    ('name', models.CharField(max_length=12)),
                ],
            ),
            migrations.AddField(
                model_name='encounter',
                name='patient',
                field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eav.Patient'),
            )
        ]
else:
    class Migration(migrations.Migration):
        dependencies = [
            ('eav', '0001_initial'),
        ]
        operations = []